server {
    listen 80;

    # 🖥️ El proxy redirige todo el tráfico al contenedor del portfolio
    location / {
        proxy_pass http://portfolio-front:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}